[package]
name="insurance_claim"
type="bin"
authors = ["masaun"]
compiler_version = ">=0.31.0"

[dependencies]
ecrecover = { tag = "v0.19.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
#ecrecover = {tag = "v0.16.1", git = "https://github.com/signorecello/ecrecover-noir.git"}