# return = ""
root = ""                  # @dev - Merkle Root
hash_path = ["", ""]
index = ""
secret = ""                # @dev - A hidden metadata hash (private)
nullifier = ""             # @dev - Should be a Poseidon2 Hash


###########################################
# @dev - InsurancePolicyData Struct data #
###########################################
[insurance_policy_data]
patient_name = ""                       # @dev - The patient name
start_date = ""                         # @dev - The start date of the insurance policy (UNIX timestamp)
end_date = ""                           # @dev - The end date of the insurance policy (UNIX timestamp)
minimum_threshold_of_bill_amount = ""   # @dev - The minimum threshold for the insurance claim
treatment_icd_code = ""                 # @dev - The treatment details to be covered by a insurance policy (ICD code)
treatment_cpt_code = ""                 # @dev - The treatment details to be covered by a insurance policy (CPT code)
treatment_hcpcs_code = ""               # @dev - The treatment details to be covered by a insurance policy (HCPCS code)     
treatment_drg_code = ""                 # @dev - The treatment details to be covered by a insurance policy (DRG code)


#########################################
# @dev - HospitalBillData Struct data #
#########################################
[hospital_bill_data]
# @dev - The insurance claim related input data
hospital_bill_hash_bytes = []   # @dev - The hash of the hospital bill
#hospital_bill_hash = "" # @dev - The hash of the hospital bill
hospital_bill_amount = ""       # @dev - The insurance claim related input parameters

hospital_pubkey_bytes = []   # @dev - The public key of the hospital

hospital_signature_bytes = []
#hospital_signature_bytes = "" # @dev - The signature from the hospital

patient_name = ""                       # @dev - The patient name
treatment_date = ""                     # @dev - The treatment date (UNIX timestamp)
treatment_icd_code = ""                 # @dev - The treatment details (ICD code)
treatment_cpt_code = ""                 # @dev - The treatment details (CPT code)
treatment_hcpcs_code = ""               # @dev - The treatment details (HCPCS code)     
treatment_drg_code = ""                 # @dev - The treatment details (DRG code)

