# return = ""
root = ""                  # @dev - Merkle Root
hash_path = ["", ""]
index = ""
secret = ""                # @dev - A hidden metadata hash (private)
expected_nullifier = ""    # @dev - Should be a Poseidon2 Hash
expected_nft_metadata_cid_hash = "" # @dev - Should be a Poseidon2 Hash



#################################################
# @dev - The insurance claim related input data #
#################################################

# @dev - The insurance claim related input data
hospital_bill_hash_bytes = []   # @dev - The hash of the hospital bill
#hospital_bill_hash = "" # @dev - The hash of the hospital bill
hospital_bill_amount = ""       # @dev - The insurance claim related input parameters

pubkey_of_hospital_bytes = []   # @dev - The public key of the hospital

signature_from_hospital_bytes = []
#signature_from_hospital = "" # @dev - The signature from the hospital

authorized_healthcare_provider_pubkey = ""                # @dev - This public key should be validated on-chain with a on-chain registry.
expected_authorized_healthcare_provider_pubkey_hash = ""  # @dev - The expected public key hash of the authorized healthcare provider



#################################################
# @dev - Struct data #
#################################################

# @dev - The IPNFTData struct
[ip_nft_data]
nft_owner = ""
nft_token_id = ""
nft_metadata_cid = ""      # @dev - IPFS CID, which is not hashed yet. (i.e. "QmYwAPJzv5CZsnAzt8auVZRn5W4mBkpLsD4HaBFN6r5y6F")
#nft_metadata_hash = ""

# root: pub Field, // @dev - Merkle Root
# hash_path: [Field; 2],
# index: Field,
# secret: Field,   // @dev - A hidden metadata hash (private)
# ip_nft_data: IPNftData

# pub struct IPNftData {
#     nft_owner: Field,
#     nft_token_id: Field,
#     nft_metadata_hash: Field  // IPFS CID for the metadata of NFT, which is generated when uploading to IPFS.
# }