# return = ""
root = ""                  # @dev - Merkle Root
hash_path = ["", ""]
index = ""
secret = ""                # @dev - A hidden metadata hash (private)
nullifier = ""             # @dev - Should be a Poseidon2 Hash


#########################################
# @dev - HospitalBillData Struct data #
#########################################

[hospital_bill_data]
# @dev - The insurance claim related input data
hospital_bill_hash_bytes = []   # @dev - The hash of the hospital bill
#hospital_bill_hash = "" # @dev - The hash of the hospital bill
hospital_bill_amount = ""       # @dev - The insurance claim related input parameters

hospital_pubkey_bytes = []   # @dev - The public key of the hospital

hospital_signature_bytes = []
#hospital_signature_bytes = "" # @dev - The signature from the hospital