# return = ""
root = ""                  # @dev - Merkle Root
hash_path = ["", ""]
index = ""
secret = ""                # @dev - A hidden metadata hash (private)
nullifier = ""             # @dev - Should be a Poseidon2 Hash


###########################################
# @dev - InsurancePolicyData Struct data #
###########################################
[insurance_policy_data]
insurer_pubkey_bytes = []               # @dev - The public key of the insurer
insurer_signature_bytes = []            # @dev - The signature from the insurer
patient_name = ""                       # @dev - The patient name
start_date = ""                         # @dev - The start date of the insurance policy (UNIX timestamp)
end_date = ""                           # @dev - The end date of the insurance policy (UNIX timestamp)
minimum_threshold_of_bill_amount = ""   # @dev - The minimum threshold for the insurance claim
treatment_icd_code = ""                 # @dev - The treatment details to be covered by a insurance policy (ICD code)
treatment_cpt_code = ""                 # @dev - The treatment details to be covered by a insurance policy (CPT code)
treatment_hcpcs_code = ""               # @dev - The treatment details to be covered by a insurance policy (HCPCS code)     
treatment_drg_code = ""                 # @dev - The treatment details to be covered by a insurance policy (DRG code)


#########################################
# @dev - HospitalBillData Struct data #
#########################################
[hospital_bill_data]
hospital_bill_hash_bytes = []           # @dev - The hash of the hospital bill
hospital_bill_amount = ""               # @dev - The insurance claim related input parameters
hospital_pubkey_bytes = []              # @dev - The public key of the hospital
hospital_signature_bytes = []           # @dev - The signature from the hospital
patient_name = ""                       # @dev - The patient name
treatment_date = ""                     # @dev - The treatment date (UNIX timestamp)
treatment_icd_code = ""                 # @dev - The treatment details (ICD code)
treatment_cpt_code = ""                 # @dev - The treatment details (CPT code)
treatment_hcpcs_code = ""               # @dev - The treatment details (HCPCS code)     
treatment_drg_code = ""                 # @dev - The treatment details (DRG code)



#########################################
# @dev - Example values for testing     #
#########################################

# @dev - Source: https://github.com/colinnielsen/ecrecover-noir/blob/main/Prover.toml

# x + y of hardhat 0 address:
# private key = ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
# pub key = 0x8318535b54105d4a7aae60c08fc45f9687181b4fdfc625bd1a753fa7397fed753547f11ca8696646f2f3acb08e31016afac23e630c5d11f59f61fef57b0d2aa5
# keccak of pub key = 0xc1ffd3cfee2d9e5cd67643f8f39fd6e51aad88f6f4ce6ab8827279cfffb92266
# addr (right most 20 bytes) 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
pub_key_x = [131,24,83,91,84,16,93,74,122,174,96,192,143,196,95,150,135,24,27,79,223,198,37,189,26,117,63,167,57,127,237,117]
pub_key_y = [53,71,241,28,168,105,102,70,242,243,172,176,142,49,1,106,250,194,62,99,12,93,17,245,159,97,254,245,123,13,42,165]
signature = [57,17,112,239,241,30,64,157,170,50,85,145,156,69,226,85,147,164,10,82,71,93,42,132,200,220,161,255,95,241,211,141,81,7,150,25,25,27,162,213,80,61,12,170,50,4,154,203,252,229,119,29,202,153,50,25,126,145,245,23,136,75,29,177]
hashed_message = [13,82,120,60,76,186,215,235,175,126,185,67,252,100,143,82,130,165,32,112,68,47,193,141,141,209,109,219,47,203,175,102] # hi